package org.example.util.enums;

import lombok.NoArgsConstructor;

@NoArgsConstructor
public enum Scope {
  LOCALIZED_RESOURCES,
  LOCALIZED_PROPERTIES,
  QUOTATION,
  SPACING,
  MULTIPLICATION_CHARACTER_USAGE,
  HYPHEN_CHARACTER_USAGE,
  NUMBERING_USAGE,
  THOUSAND_SEPARATOR,
  NUMBER_FRACTION,
  HTML_CHARACTER_USAGE,
  UNUSED_LITHUANIAN_WORDS,
  MULTIPLE_UPPERCASE_USAGE
}
